<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_GreenConveyor" Id="{120bdc55-22e1-42a9-8b1f-b54ef0d19c05}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_GreenConveyor
VAR
	Motor					:FB_ConveyorMotor;
	LTU						:FB_LTU_Cylinder;	
    BlueStopper				:FB_Stopper;
    nStatus					:INT:=0;	
				
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_GreenConveyor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>